# Generated by Django 2.1.5 on 2019-01-24 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='نام تیم')),
                ('nickname', models.CharField(max_length=64, verbose_name='لقب تیم')),
                ('internatinalRank', models.IntegerField(verbose_name='رتبه جهانی')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='شهر')),
                ('country', models.CharField(blank=True, help_text='اجباری نیست.', max_length=32, verbose_name='کشور')),
                ('establishedYear', models.IntegerField(verbose_name='سال تاسیس')),
                ('coach', models.CharField(max_length=32, verbose_name='سرمربی')),
                ('captain', models.CharField(max_length=32, verbose_name='کاپیتان')),
                ('website', models.URLField(verbose_name='وب سایت')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر لیگ')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'تیم',
                'ordering': ('-created_date_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TeamSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='لیگ')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر تیم',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
    ]
