# Generated by Django 2.1.5 on 2019-02-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر تیم',
                'verbose_name_plural': 'تصاویر اسلایدر تیم ها',
                'ordering': ('-created_date_time', 'team'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'team')},
        ),
    ]
