# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190124_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created_date_time', 'name'), 'verbose_name': 'تیم', 'verbose_name_plural': 'تیم ها'},
        ),
        migrations.AlterModelOptions(
            name='teamsliderimage',
            options={'ordering': ('-created_date_time', 'title'), 'verbose_name': 'تصویر اسلایدر تیم', 'verbose_name_plural': 'تصاویر اسلایدر تیم ها'},
        ),
    ]
