# Generated by Django 2.1.5 on 2019-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190131_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image_url',
            field=models.URLField(verbose_name='آدرس تصویر تیم'),
        ),
    ]
