# Generated by Django 2.1.5 on 2019-02-02 00:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0004_auto_20190201_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeTeam',
        ),
    ]
