# Generated by Django 2.1.5 on 2019-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_date_time', models.DateTimeField()),
                ('image_url', models.URLField(blank=True)),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
    ]
