# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ('-created_date_time', 'title'), 'verbose_name': 'تصویر اسلایدر اصلی', 'verbose_name_plural': 'تصاویر اسلایدر اصلی'},
        ),
    ]
