# Generated by Django 2.1.5 on 2019-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(default='', max_length=32, primary_key=True, serialize=False, verbose_name='نام تگ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='درباره ی تگ')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'تگ',
                'ordering': ('-created_date_time', 'name'),
            },
        ),
    ]
