# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_date_time', 'name'), 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
