# Generated by Django 2.1.5 on 2019-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=63, unique=True, verbose_name='نام تگ'),
        ),
    ]
