# Generated by Django 2.1.5 on 2019-01-24 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('summary', models.CharField(blank=True, max_length=256, null=True, verbose_name='خلاصه خبر')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('category', models.CharField(max_length=16, null=True, verbose_name='نوع خبر')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'خبر',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
    ]
