# Generated by Django 2.1.5 on 2019-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='عنوان')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='خلاصه خبر')),
                ('text', models.TextField(blank=True, verbose_name='متن خبر')),
                ('category', models.CharField(max_length=31, verbose_name='نوع خبر')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title',)},
        ),
    ]
