# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_date_time', 'title'), 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
