# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190123_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(null=True, to='news.Tag'),
        ),
    ]
