# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190123_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
