# Generated by Django 2.1.5 on 2019-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190201_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date_time',
            field=models.DateTimeField(verbose_name='زمان ساخت'),
        ),
    ]
