# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_date_time', 'title'), 'verbose_name': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='created_date_time',
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.Tag'),
        ),
    ]
