# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-23 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190123_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sumery',
            new_name='summary',
        ),
    ]
