# Generated by Django 2.1.5 on 2019-01-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='نام لیگ')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('confederation', models.CharField(max_length=31, verbose_name='کنفدراسیون')),
                ('country', models.CharField(blank=True, help_text='الزامی نیست.', max_length=31, verbose_name='کشور')),
                ('level', models.IntegerField(blank=True, verbose_name='دسته')),
                ('numberOfTeams', models.IntegerField(verbose_name='تعداد تیم ها')),
                ('bestTeam', models.CharField(blank=True, max_length=63, verbose_name='بهترین تیم')),
                ('establishedYear', models.IntegerField(verbose_name='سال تاسیس')),
                ('website', models.URLField(blank=True, verbose_name='وب سایت')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر لیگ')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'لیگ',
                'verbose_name_plural': 'لیگ ها',
                'ordering': ('-created_date_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LeagueSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='عنوان')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League', verbose_name='لیگ')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر لیگ',
                'verbose_name_plural': 'تصاویر اسلایدر لیگ',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name', 'year')},
        ),
    ]
