# Generated by Django 2.1.5 on 2019-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tag.Tag', verbose_name='تگ ها'),
        ),
    ]
