# Generated by Django 2.1.5 on 2019-01-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190128_2119'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name='عنوان')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League', verbose_name='لیگ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'برترین بازیکن',
                'verbose_name_plural': 'برترین بازیکنان',
                'ordering': ('-created_date_time', 'player'),
            },
        ),
    ]
