# Generated by Django 2.1.5 on 2019-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190128_2119'),
        ('leagues', '0002_bestplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestPlayers',
            new_name='BestPlayer',
        ),
    ]
