# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20190124_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-created_date_time', 'name'), 'verbose_name': 'لیگ', 'verbose_name_plural': 'لیگ ها'},
        ),
        migrations.AlterModelOptions(
            name='leaguesliderimage',
            options={'ordering': ('-created_date_time', 'title'), 'verbose_name': 'تصویر اسلایدر لیگ', 'verbose_name_plural': 'تصاویر اسلایدر لیگ'},
        ),
    ]
