# Generated by Django 2.1.5 on 2019-01-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='نام')),
                ('nationality', models.CharField(max_length=31, verbose_name='ملیت')),
                ('placeBirth', models.CharField(max_length=31, verbose_name='محل تولد')),
                ('team', models.CharField(blank=True, max_length=63, verbose_name='باشگاه')),
                ('age', models.IntegerField(blank=True, verbose_name='سن')),
                ('height', models.FloatField(blank=True, verbose_name='قد')),
                ('weight', models.IntegerField(blank=True, verbose_name='وزن')),
                ('teamNum', models.IntegerField(blank=True, verbose_name='شماره پیراهن در باشگاه')),
                ('nationalityTeamNum', models.IntegerField(blank=True, verbose_name='شماره پیراهن در تیم ملی')),
                ('website', models.URLField(blank=True, verbose_name='وب سایت')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر بازیکن')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='FTB', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'بازیکن',
                'verbose_name_plural': 'بازیکنان',
                'ordering': ('-created_date_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlayerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='نام')),
                ('short_name', models.CharField(max_length=3, verbose_name='نام مخفف')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='FTB', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'پست بازیکن',
                'verbose_name_plural': 'پست های بازیکنان',
                'ordering': ('name', 'short_name'),
            },
        ),
        migrations.CreateModel(
            name='PlayerSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='عنوان')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر بازیکن',
                'verbose_name_plural': 'تصاویر اسلایدر بازیکن',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.PlayerPost', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='player',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها'),
        ),
    ]
