# Generated by Django 2.1.5 on 2019-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationalityTeamNum',
            field=models.IntegerField(verbose_name='شماره پیراهن در تیم ملی'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamNum',
            field=models.IntegerField(verbose_name='شماره پیراهن در باشگاه'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(verbose_name='وزن'),
        ),
    ]
