# Generated by Django 2.1.5 on 2019-01-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='نام')),
                ('short_name', models.CharField(max_length=3, verbose_name='نام مخفف')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'پست بازیکن',
                'verbose_name_plural': 'پست های بازیکنان',
                'ordering': ('name', 'short_name'),
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player.PlayerPost', verbose_name='پست'),
        ),
    ]
