# Generated by Django 2.1.5 on 2019-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190124_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('-created_date_time', 'name'), 'verbose_name': 'بازیکن', 'verbose_name_plural': 'بازیکنان'},
        ),
        migrations.AlterModelOptions(
            name='playersliderimage',
            options={'ordering': ('-created_date_time', 'title'), 'verbose_name': 'تصویر اسلایدر بازیکن', 'verbose_name_plural': 'تصاویر اسلایدر بازیکن'},
        ),
    ]
