# Generated by Django 2.1.5 on 2019-01-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190128_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.PlayerPost', verbose_name='پست'),
        ),
    ]
