# Generated by Django 2.1.5 on 2019-01-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190128_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersliderimage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
    ]
