# Generated by Django 2.1.5 on 2019-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190201_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationalityTeamNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره پیراهن در تیم ملی'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره پیراهن در باشگاه'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
