# Generated by Django 2.1.5 on 2019-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190128_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='city',
            new_name='placeBirth',
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='player',
            name='field',
            field=models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='FTB', max_length=3, verbose_name='ورزش'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=63, verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='playerpost',
            name='field',
            field=models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='FTB', max_length=3, verbose_name='ورزش'),
        ),
    ]
