# Generated by Django 2.1.5 on 2019-02-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0005_auto_20190201_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
                'ordering': ('-created_date_time', 'player'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='likeplayer',
            unique_together={('user', 'player')},
        ),
    ]
