# Generated by Django 2.1.5 on 2019-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='field',
            field=models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='FTB', max_length=3, verbose_name='ورزش'),
        ),
    ]
