# Generated by Django 2.1.5 on 2019-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('team_in_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('player', models.ForeignKey(on_delete=True, to='player.Player', verbose_name='بازیکن')),
                ('teamLeague', models.ForeignKey(on_delete=True, to='team_in_league.TeamLeague', verbose_name='تیم در لیگ')),
            ],
            options={
                'verbose_name': 'حضور بازیکن در تیم',
                'verbose_name_plural': 'حضور بازیکن ها در تیم ها',
                'ordering': ('-created_date_time', 'player'),
            },
        ),
    ]
