# Generated by Django 2.1.5 on 2019-01-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_in_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteam',
            name='num',
            field=models.IntegerField(default=0, verbose_name='شماره پیراهن'),
        ),
    ]
