# Generated by Django 2.1.5 on 2019-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_in_team', '0002_playerteam_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerteam',
            name='num',
            field=models.IntegerField(verbose_name='شماره پیراهن'),
        ),
    ]
