# Generated by Django 2.1.5 on 2019-01-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('tag', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals1', models.IntegerField(verbose_name='گل های تیم ۱')),
                ('goals2', models.IntegerField(verbose_name='گل های تیم ۲')),
                ('shots1', models.IntegerField(verbose_name='شوت های تیم ۱')),
                ('shots2', models.IntegerField(verbose_name='شوت های تیم ۲')),
                ('shots_on_target1', models.IntegerField(verbose_name='شوت های داخل چارچوب تیم ۱')),
                ('shots_on_target2', models.IntegerField(verbose_name='شوت های داخل چارچوب تیم ۲')),
                ('possession1', models.IntegerField(verbose_name='مالکیت توپ تیم ۱')),
                ('possession2', models.IntegerField(verbose_name='مالکیت توپ تیم ۲')),
                ('passes1', models.IntegerField(verbose_name='پاس های تیم ۱')),
                ('passes2', models.IntegerField(verbose_name='پاس های تیم ۲')),
                ('fouls1', models.IntegerField(verbose_name='خطا های تیم۱')),
                ('fouls2', models.IntegerField(verbose_name='خطا های تیم۱')),
                ('yellow_cards1', models.IntegerField(verbose_name='کارت زرد های تیم ۱')),
                ('yellow_cards2', models.IntegerField(verbose_name='کارت زرد های تیم ۲')),
                ('red_cards1', models.IntegerField(verbose_name='کارت قرمز های تیم ۱')),
                ('red_cards2', models.IntegerField(verbose_name='کارت قرمز های تیم ۲')),
                ('offsides1', models.IntegerField(verbose_name='آفساید های تیم ۱')),
                ('offsides2', models.IntegerField(verbose_name='آفساید های تیم ۲')),
                ('corners1', models.IntegerField(verbose_name='کرنر های تیم ۱')),
                ('corners2', models.IntegerField(verbose_name='کرنر های تیم ۲')),
                ('game_date', models.DateTimeField(verbose_name='تاریخ و ساعت بازی')),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball')], default='OTH', max_length=3, verbose_name='ورزش')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('league', models.ForeignKey(on_delete=True, to='leagues.League', verbose_name='لیگ')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها')),
                ('team1', models.ForeignKey(on_delete=True, related_name='host', to='team.Team', verbose_name='تیم۱')),
                ('team2', models.ForeignKey(on_delete=True, related_name='guest', to='team.Team', verbose_name='تیم۲')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی ها',
                'ordering': ('-created_date_time', 'team1', 'team2', 'league'),
            },
        ),
        migrations.CreateModel(
            name='GameSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='عنوان')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر بازی',
                'verbose_name_plural': 'تصاویر اسلایدر بازی ها',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
    ]
