# Generated by Django 2.1.5 on 2019-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('leagues', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('team1', 'team2', 'league', 'game_date')},
        ),
    ]
