# Generated by Django 2.1.5 on 2019-01-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistgoal',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Goal', verbose_name='گل'),
        ),
    ]
