# Generated by Django 2.1.5 on 2019-01-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('tag', '0001_initial'),
        ('team', '0001_initial'),
        ('leagues', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowcard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='yellowcard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='redcard',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='redcard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='redcard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='penaltygoal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='penaltygoal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='penaltygoal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='gamesliderimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='gamereport',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League', verbose_name='لیگ'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='تگ ها'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='team.Team', verbose_name='تیم۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='team.Team', verbose_name='تیم۲'),
        ),
        migrations.AddField(
            model_name='assistgoal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='assistgoal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='assistgoal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
        migrations.AlterUniqueTogether(
            name='gamereport',
            unique_together={('title', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('team1', 'team2', 'league', 'game_date')},
        ),
    ]
