# Generated by Django 2.1.5 on 2019-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190201_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='possession1',
            field=models.IntegerField(default=0, help_text='برای بازی فوتبال', verbose_name='مالکیت توپ تیم ۱'),
            preserve_default=False,
        ),
    ]
