# Generated by Django 2.1.5 on 2019-01-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190125_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesliderimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
    ]
