# Generated by Django 2.1.5 on 2019-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190127_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltygoal',
            name='game',
        ),
        migrations.RemoveField(
            model_name='penaltygoal',
            name='player',
        ),
        migrations.RemoveField(
            model_name='penaltygoal',
            name='receiving_team',
        ),
        migrations.RemoveField(
            model_name='penaltygoal',
            name='scoring_team',
        ),
        migrations.AddField(
            model_name='goal',
            name='penalty',
            field=models.BooleanField(default=False, verbose_name='پنالتی'),
        ),
        migrations.DeleteModel(
            name='PenaltyGoal',
        ),
    ]
