# Generated by Django 2.1.5 on 2019-01-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190125_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='عنوان')),
                ('image_url', models.URLField(verbose_name='آدرس تصویر')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('game', models.ForeignKey(on_delete=True, to='game.Game', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'گزارش بازی\u200c',
                'verbose_name_plural': 'گزارشات بازی',
                'ordering': ('-created_date_time', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='gamereport',
            unique_together={('title', 'game')},
        ),
    ]
