# Generated by Django 2.1.5 on 2019-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190125_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereport',
            name='slug',
        ),
        migrations.AddField(
            model_name='gamereport',
            name='minute',
            field=models.IntegerField(default=0, verbose_name='دقیقه'),
        ),
        migrations.AddField(
            model_name='gamereport',
            name='second',
            field=models.IntegerField(default=0, verbose_name='ثانیه'),
        ),
    ]
