# Generated by Django 2.1.5 on 2019-01-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190127_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_state1',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Lose')], max_length=1, verbose_name='نتیجه بازی ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_state2',
            field=models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Lose')], max_length=1, verbose_name='نتیجه بازی ۲'),
        ),
    ]
