# Generated by Django 2.1.5 on 2019-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190127_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='field',
            field=models.CharField(choices=[('FTB', 'فوتبال'), ('BSK', 'بسکتبال')], default='OTH', max_length=3, verbose_name='ورزش'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_state1',
            field=models.CharField(choices=[('W', 'برنده'), ('D', 'تساوی'), ('L', 'بازنده')], max_length=1, verbose_name='نتیجه بازی ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_state2',
            field=models.CharField(choices=[('W', 'برنده'), ('D', 'تساوی'), ('L', 'بازنده')], max_length=1, verbose_name='نتیجه بازی ۲'),
        ),
    ]
