# Generated by Django 2.1.5 on 2019-02-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190201_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='all_score1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', null=True, verbose_name='امتیاز تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='all_score2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', null=True, verbose_name='امتیاز تیم ۲'),
        ),
    ]
