# Generated by Django 2.1.5 on 2019-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190201_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ribbond2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', null=True, verbose_name='ریباند تیم ۲'),
        ),
    ]
