# Generated by Django 2.1.5 on 2019-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190127_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='corners1',
            field=models.IntegerField(blank=True, verbose_name='کرنر های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='corners2',
            field=models.IntegerField(blank=True, verbose_name='کرنر های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='fouls1',
            field=models.IntegerField(blank=True, verbose_name='خطا های تیم۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='fouls2',
            field=models.IntegerField(blank=True, verbose_name='خطا های تیم۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals1',
            field=models.IntegerField(blank=True, verbose_name='گل های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals2',
            field=models.IntegerField(blank=True, verbose_name='گل های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='offsides1',
            field=models.IntegerField(blank=True, verbose_name='آفساید های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='offsides2',
            field=models.IntegerField(blank=True, verbose_name='آفساید های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='passes1',
            field=models.IntegerField(blank=True, verbose_name='پاس های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='passes2',
            field=models.IntegerField(blank=True, verbose_name='پاس های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='possession1',
            field=models.IntegerField(blank=True, verbose_name='مالکیت توپ تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='possession2',
            field=models.IntegerField(blank=True, verbose_name='مالکیت توپ تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_cards1',
            field=models.IntegerField(blank=True, verbose_name='کارت قرمز های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_cards2',
            field=models.IntegerField(blank=True, verbose_name='کارت قرمز های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots1',
            field=models.IntegerField(blank=True, verbose_name='شوت های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots2',
            field=models.IntegerField(blank=True, verbose_name='شوت های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots_on_target1',
            field=models.IntegerField(blank=True, verbose_name='شوت های داخل چارچوب تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots_on_target2',
            field=models.IntegerField(blank=True, verbose_name='شوت های داخل چارچوب تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_state1',
            field=models.CharField(blank=True, choices=[('W', 'برنده'), ('D', 'تساوی'), ('L', 'بازنده')], max_length=1, verbose_name='نتیجه بازی ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_state2',
            field=models.CharField(blank=True, choices=[('W', 'برنده'), ('D', 'تساوی'), ('L', 'بازنده')], max_length=1, verbose_name='نتیجه بازی ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='yellow_cards1',
            field=models.IntegerField(blank=True, verbose_name='کارت زرد های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='yellow_cards2',
            field=models.IntegerField(blank=True, verbose_name='کارت زرد های تیم ۲'),
        ),
    ]
