# Generated by Django 2.1.5 on 2019-01-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190128_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full_time',
            field=models.BooleanField(default=False, verbose_name='بازی انجام شده'),
        ),
    ]
