# Generated by Django 2.1.5 on 2019-02-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('player', '0005_auto_20190201_1136'),
        ('game', '0007_auto_20190201_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(verbose_name='دقیقه')),
                ('second', models.IntegerField(verbose_name='ثانیه')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'اخراج',
                'verbose_name_plural': 'اخراج ها(مخصوص بازی بسکتبال)',
                'ordering': ('-created_date_time', 'game'),
            },
        ),
    ]
