# Generated by Django 2.1.5 on 2019-02-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_sendoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='score',
            field=models.CharField(choices=[('1', 'پرتاب ۱ امتیازی'), ('2', 'پرتاب ۲ امتیازی'), ('3', 'پرتاب ۳ امتیازی')], max_length=1, verbose_name='نوع پرتاب'),
        ),
    ]
