# Generated by Django 2.1.5 on 2019-01-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190128_1001'),
        ('team', '0001_initial'),
        ('game', '0009_auto_20190128_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(verbose_name='دقیقه')),
                ('second', models.IntegerField(verbose_name='ثانیه')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی')),
                ('in_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_player', to='player.Player', verbose_name='بازیکن وارد شده')),
                ('out_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_player', to='player.Player', verbose_name='بازیکن خارج شده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'کارت زرد\u200c',
                'verbose_name_plural': 'کارت های زرد',
                'ordering': ('-created_date_time', 'game'),
            },
        ),
    ]
