# Generated by Django 2.1.5 on 2019-01-31 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20190131_1335'),
        ('game', '0015_goal_own_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'پاس گل',
                'verbose_name_plural': 'پاس های گل(مخصوص بازی بسکتبال)',
                'ordering': ('-created_date_time', 'throw'),
            },
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(verbose_name='دقیقه')),
                ('second', models.IntegerField(verbose_name='ثانیه')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'خطا',
                'verbose_name_plural': 'خطاها (مخصوص بازی بسکتبال)',
                'ordering': ('-created_date_time', 'game'),
            },
        ),
        migrations.CreateModel(
            name='Ribbond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(verbose_name='دقیقه')),
                ('second', models.IntegerField(verbose_name='ثانیه')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'ریباند',
                'verbose_name_plural': 'ریباندها (مخصوص بازی بسکتبال)',
                'ordering': ('-created_date_time', 'game'),
            },
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name=((1, 'پرتاب ۱ امتیازی'), (2, 'پرتاب ۲ امتیازی'), (3, 'پرتاب ۳ امتیازی')))),
                ('minute', models.IntegerField(verbose_name='دقیقه')),
                ('second', models.IntegerField(verbose_name='ثانیه')),
                ('created_date_time', models.DateTimeField(verbose_name='زمان ساخت')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'پرتاب',
                'verbose_name_plural': 'پرتاب ها(مخصوص بازی بسکتبال)',
                'ordering': ('-created_date_time', 'game'),
            },
        ),
        migrations.AlterModelOptions(
            name='assistgoal',
            options={'ordering': ('-created_date_time', 'goal'), 'verbose_name': 'پاس گل', 'verbose_name_plural': 'پاس های گل(مخصوص بازی فوتبال)'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-created_date_time', 'game'), 'verbose_name': 'گل', 'verbose_name_plural': 'گل ها(مخصوص بازی فوتبال)'},
        ),
        migrations.AlterModelOptions(
            name='redcard',
            options={'ordering': ('-created_date_time', 'game'), 'verbose_name': 'کارت قرمز', 'verbose_name_plural': 'کارت های قرمز(مخصوص بازی فوتبال)'},
        ),
        migrations.AlterModelOptions(
            name='yellowcard',
            options={'ordering': ('-created_date_time', 'game'), 'verbose_name': 'کارت زرد\u200c', 'verbose_name_plural': 'کارت های زرد(مخصوص بازی فوتبال)'},
        ),
        migrations.AddField(
            model_name='game',
            name='counter_attack1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='ضدحمله های تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='counter_attack2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='ضدحمله های تیم ۲'),
        ),
        migrations.AddField(
            model_name='game',
            name='out1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='اخراج های تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='out2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='اخراج های تیم ۲'),
        ),
        migrations.AddField(
            model_name='game',
            name='ribbond1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='ریباند تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='ribbond2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='ریباند تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='score1_team1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۱ امتیازی تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='score1_team2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۱ امتیازی تیم ۲'),
        ),
        migrations.AddField(
            model_name='game',
            name='score2_team1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۲ امتیازی تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='score2_team2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۲ امتیازی تیم ۲'),
        ),
        migrations.AddField(
            model_name='game',
            name='score3_team1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۳ امتیازی تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='score3_team2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۳ امتیازی تیم ۲'),
        ),
        migrations.AddField(
            model_name='game',
            name='style1',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='استیل های تیم ۱'),
        ),
        migrations.AddField(
            model_name='game',
            name='style2',
            field=models.IntegerField(blank=True, default=0, help_text='برای بازی بسکتبال', verbose_name='استیل های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='corners1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کرنر های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='corners2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کرنر های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='گل های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='گل های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='offsides1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='آفساید های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='offsides2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='آفساید های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='passes1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='پاس های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='passes2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='پاس های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='possession1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='مالکیت توپ تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='possession2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='مالکیت توپ تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_cards1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کارت قرمز های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_cards2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کارت قرمز های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='شوت های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='شوت های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots_on_target1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='شوت های داخل چارچوب تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='shots_on_target2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='شوت های داخل چارچوب تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='yellow_cards1',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کارت زرد های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='yellow_cards2',
            field=models.IntegerField(blank=True, help_text='برای بازی فوتبال', verbose_name='کارت زرد های تیم ۲'),
        ),
        migrations.AddField(
            model_name='throw',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='throw',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='ribbond',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='ribbond',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='foul',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='foul',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='assistthrow',
            name='throw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Throw', verbose_name='پرتاب'),
        ),
    ]
