# Generated by Django 2.1.5 on 2019-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20190131_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='counter_attack1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='ضدحمله های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_attack2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='ضدحمله های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='out1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='اخراج های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='out2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='اخراج های تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ribbond1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='ریباند تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ribbond2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='ریباند تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score1_team1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۱ امتیازی تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score1_team2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۱ امتیازی تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2_team1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۲ امتیازی تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2_team2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۲ امتیازی تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score3_team1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۳ امتیازی تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score3_team2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='پرتاب های ۳ امتیازی تیم ۲'),
        ),
        migrations.AlterField(
            model_name='game',
            name='style1',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='استیل های تیم ۱'),
        ),
        migrations.AlterField(
            model_name='game',
            name='style2',
            field=models.IntegerField(blank=True, help_text='برای بازی بسکتبال', verbose_name='استیل های تیم ۲'),
        ),
    ]
