# Generated by Django 2.1.5 on 2019-01-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='fix',
            field=models.BooleanField(default=True, verbose_name='بازیکن ثابت'),
        ),
    ]
