# Generated by Django 2.1.5 on 2019-01-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0002_auto_20190126_1316'),
        ('membership', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='teamLeague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.TeamLeague', verbose_name='تیم در لیگ'),
        ),
        migrations.AddField(
            model_name='playergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='بازی'),
        ),
        migrations.AddField(
            model_name='playergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='بازیکن'),
        ),
        migrations.AddField(
            model_name='playergame',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='تیم'),
        ),
    ]
