# Generated by Django 2.1.5 on 2019-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='minute',
            field=models.IntegerField(default=0, verbose_name='مدت زمان بازی در تیم'),
        ),
    ]
