# Generated by Django 2.1.5 on 2019-02-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_playergame_minute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergame',
            old_name='minute',
            new_name='time',
        ),
    ]
